### ISSUE TITLE
missing light config file?

### ISSUE THREAD

**Issue by tomh05** [danrspencer/hass-config#1]
Hi,

I'm using your config a inspiration - is there a missing `configuration/light` file?

**Comment by danrspencer** [comment]
Hi,

Everything I use in HA is in GitHub, although most of my automations are now done via NodeRed which isn't totally up to date in GitHub.

What are you missing?

**Comment by tomh05** [comment]
Ah, my apologies. I'd assumed there was a missing light folder, as configuration.yaml referred to it. I've now learnt more about hassio and realised some lights don't need a config file.
